from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import csv
from typing import Iterable, Literal

from .base import BenchmarkArtifact, GenerationResult


@dataclass
class TPCDSData(BenchmarkArtifact):
    """Generate TPC-DS data-generation artifacts."""

    scale_factor: int | float = 10
    mode: Literal["synth", "plan"] = "synth"

    benchmark: str = "tpcds"
    artifact_type: str = "data"

    def generate(self, output_dir: str | Path | None) -> GenerationResult:
        root = self._require_output_dir(output_dir)
        out_dir = root / "tpcds" / "data"
        out_dir.mkdir(parents=True, exist_ok=True)

        if self.mode == "synth":
            files = self._generate_synthetic_tables(out_dir)
            metadata = self._write_json(
                out_dir / "tpcds_data_manifest.json",
                {
                    "benchmark": self.benchmark,
                    "artifact_type": self.artifact_type,
                    "scale_factor": self.scale_factor,
                    "mode": self.mode,
                    "files": self._paths_relative_to(root, files),
                    "note": (
                        "Synthetic TPC-DS-like data generated locally for quick onboarding "
                        "and API validation."
                    ),
                },
            )
            return self._result(root, files, metadata)

        script = self._write_text(out_dir / "generate_tpcds_data.sh", self._script_body())
        script.chmod(0o755)

        readme = self._write_text(
            out_dir / "README.md",
            (
                "# TPC-DS Data Generation\n\n"
                "This folder is generated by DriftBench.\n\n"
                "Run the script below to generate tables into this directory.\n"
                "The script writes data under `./tables`.\n"
            ),
        )

        metadata = self._write_json(
            out_dir / "tpcds_data_manifest.json",
            {
                "benchmark": self.benchmark,
                "artifact_type": self.artifact_type,
                "scale_factor": self.scale_factor,
                "mode": self.mode,
                "files": self._paths_relative_to(root, [script, readme]),
                "note": "TPC-DS data is generated externally by dsdgen; DriftBench exports reproducible generation scripts.",
            },
        )
        return self._result(root, [script, readme], metadata)

    def _script_body(self) -> str:
        return (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n\n"
            f"SCALE_FACTOR={self.scale_factor}\n"
            "OUT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)/tables\"\n"
            "mkdir -p \"${OUT_DIR}\"\n\n"
            "# Example: with tpcds-kit (https://github.com/gregrahn/tpcds-kit)\n"
            "# 1) cd tools\n"
            "# 2) make\n"
            "# 3) ./dsdgen -scale ${SCALE_FACTOR} -dir \"${OUT_DIR}\"\n\n"
            "echo \"Generate TPC-DS data using dsdgen into: ${OUT_DIR}\"\n"
        )

    def _generate_synthetic_tables(self, out_dir: Path) -> list[Path]:
        scale = self._scale_value()
        customer_rows = max(1, int(round(1000 * scale)))
        item_rows = max(1, int(round(500 * scale)))
        date_rows = max(1, int(round(365 * max(1.0, scale))))
        store_sales_rows = max(1, int(round(5000 * scale)))

        customer = out_dir / "customer.csv"
        item = out_dir / "item.csv"
        date_dim = out_dir / "date_dim.csv"
        store_sales = out_dir / "store_sales.csv"

        self._write_csv(
            customer,
            ["customer_sk", "customer_id", "current_cdemo_sk", "current_addr_sk", "first_name", "last_name"],
            (
                [i, f"CUST{i:09d}", (i % 1000) + 1, (i % 5000) + 1, f"First{i}", f"Last{i}"]
                for i in range(1, customer_rows + 1)
            ),
        )
        self._write_csv(
            item,
            ["item_sk", "item_id", "category", "class", "current_price"],
            (
                [i, f"ITEM{i:09d}", f"CAT{i % 20}", f"CLASS{i % 50}", f"{(i % 1000) / 10 + 1:.2f}"]
                for i in range(1, item_rows + 1)
            ),
        )
        self._write_csv(
            date_dim,
            ["date_sk", "date_id", "month_seq", "week_seq", "year", "moy", "dom"],
            (
                [i, f"D{i:09d}", (i // 30) + 1, (i // 7) + 1, 2000 + ((i // 365) % 25), ((i - 1) % 12) + 1, ((i - 1) % 28) + 1]
                for i in range(1, date_rows + 1)
            ),
        )
        self._write_csv(
            store_sales,
            ["sold_date_sk", "item_sk", "customer_sk", "quantity", "sales_price"],
            (
                [
                    (i % date_rows) + 1,
                    (i % item_rows) + 1,
                    (i % customer_rows) + 1,
                    (i % 10) + 1,
                    f"{((i % 10) + 1) * (((i % 1000) / 10) + 1):.2f}",
                ]
                for i in range(1, store_sales_rows + 1)
            ),
        )
        return [customer, item, date_dim, store_sales]

    def _scale_value(self) -> float:
        value = float(self.scale_factor)
        if value <= 0:
            raise ValueError("scale_factor must be > 0")
        return value

    def _write_csv(self, path: Path, header: list[str], rows: Iterable[list[object]]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(header)
            for row in rows:
                writer.writerow(row)


@dataclass
class TPCDSQueries(BenchmarkArtifact):
    """Generate TPC-DS query workload artifacts."""

    query_ids: Iterable[int | str] | str | None = None

    benchmark: str = "tpcds"
    artifact_type: str = "queries"

    def generate(self, output_dir: str | Path | None) -> GenerationResult:
        root = self._require_output_dir(output_dir)
        out_dir = root / "tpcds" / "queries"
        out_dir.mkdir(parents=True, exist_ok=True)

        ids = self._resolve_query_ids()
        ids_file = self._write_text(
            out_dir / "query_ids.txt",
            "\n".join(f"query{idx:02d}" for idx in ids) + "\n",
        )
        sql_file = self._write_text(
            out_dir / "tpcds_queries.sql",
            self._render_sql_bundle(ids),
        )
        benchbase_cfg = self._write_text(
            out_dir / "sample_tpcds_config.xml",
            self._benchbase_template(ids),
        )

        metadata = self._write_json(
            out_dir / "tpcds_queries_manifest.json",
            {
                "benchmark": self.benchmark,
                "artifact_type": self.artifact_type,
                "query_count": len(ids),
                "query_ids": ids,
                "files": self._paths_relative_to(root, [ids_file, sql_file, benchbase_cfg]),
                "note": (
                    "Generated query-id bundle supports full set or selected ids. "
                    "SQL bodies are deterministic templates for onboarding."
                ),
            },
        )
        return self._result(root, [ids_file, sql_file, benchbase_cfg], metadata)

    def _resolve_query_ids(self) -> list[int]:
        if self.query_ids is None or self.query_ids == "all":
            return list(range(1, 100))

        ids: list[int] = []
        for raw in self.query_ids:
            value = int(raw)
            if value < 1 or value > 99:
                raise ValueError("TPC-DS query id must be between 1 and 99.")
            ids.append(value)
        if not ids:
            raise ValueError("query_ids must not be empty.")
        # Keep order but deduplicate.
        seen: set[int] = set()
        ordered: list[int] = []
        for value in ids:
            if value in seen:
                continue
            seen.add(value)
            ordered.append(value)
        return ordered

    def _benchbase_template(self, ids: list[int]) -> str:
        weights = ",".join("1" for _ in ids)
        txns = "\n".join(
            (
                "        <transactiontype>\n"
                f"            <name>Q{idx}</name>\n"
                f"            <id>{idx}</id>\n"
                "        </transactiontype>"
            )
            for idx in ids
        )
        return (
            "<?xml version=\"1.0\"?>\n"
            "<parameters>\n"
            "    <type>POSTGRES</type>\n"
            "    <driver>org.postgresql.Driver</driver>\n"
            "    <url>jdbc:postgresql://localhost:5432/benchbase?sslmode=disable&amp;ApplicationName=tpcds</url>\n"
            "    <username>admin</username>\n"
            "    <password>password</password>\n"
            "    <terminals>1</terminals>\n"
            "    <works>\n"
            "        <work>\n"
            "            <serial>true</serial>\n"
            "            <rate>unlimited</rate>\n"
            f"            <weights>{weights}</weights>\n"
            "        </work>\n"
            "    </works>\n"
            "    <transactiontypes>\n"
            f"{txns}\n"
            "    </transactiontypes>\n"
            "</parameters>\n"
        )

    def _render_sql_bundle(self, ids: list[int]) -> str:
        chunks: list[str] = []
        for qid in ids:
            chunks.append(
                (
                    f"-- TPCDS Q{qid:02d}\n"
                    f"SELECT {qid} AS query_id, COUNT(*) AS row_count\n"
                    "FROM store_sales;\n"
                )
            )
        return "\n".join(chunks).strip() + "\n"


def data(scale_factor: int | float = 10, mode: Literal["synth", "plan"] = "synth") -> TPCDSData:
    return TPCDSData(scale_factor=scale_factor, mode=mode)


def queries(query_ids: Iterable[int | str] | str | None = None) -> TPCDSQueries:
    return TPCDSQueries(query_ids=query_ids)
