from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .base import BenchmarkArtifact, GenerationResult


@dataclass
class TPCDSData(BenchmarkArtifact):
    """Generate TPC-DS data-generation artifacts."""

    scale_factor: int | float = 10

    benchmark: str = "tpcds"
    artifact_type: str = "data"

    def generate(self, output_dir: str | Path | None = None, force: bool = False) -> GenerationResult:
        root = self._require_output_dir(output_dir)
        out_dir = root / "tpcds" / "data"
        out_dir.mkdir(parents=True, exist_ok=True)

        if not force:
            existing = self._load_existing(out_dir / "tpcds_data_manifest.json", root)
            if existing is not None:
                print(f"[driftbench] TPC-DS data already exists at {out_dir}. Reusing.")
                return existing
        print(f"[driftbench] Generating TPC-DS data (sf={self.scale_factor}) → {out_dir}")

        script = self._write_text(out_dir / "generate_tpcds_data.sh", self._script_body())
        script.chmod(0o755)

        readme = self._write_text(
            out_dir / "README.md",
            (
                "# TPC-DS Data Generation\n\n"
                "This folder is generated by DriftBench.\n\n"
                "Run the script below to generate tables into this directory.\n"
                "The script writes data under `./tables`.\n"
            ),
        )

        metadata = self._write_json(
            out_dir / "tpcds_data_manifest.json",
            {
                "benchmark": self.benchmark,
                "artifact_type": self.artifact_type,
                "scale_factor": self.scale_factor,
                "files": self._paths_relative_to(root, [script, readme]),
                "note": "TPC-DS data is generated externally by dsdgen; DriftBench exports reproducible generation scripts.",
            },
        )
        return self._result(root, [script, readme], metadata)

    def _script_body(self) -> str:
        return (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n\n"
            f"SCALE_FACTOR={self.scale_factor}\n"
            "OUT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)/tables\"\n"
            "mkdir -p \"${OUT_DIR}\"\n\n"
            "# Example: with tpcds-kit (https://github.com/gregrahn/tpcds-kit)\n"
            "# 1) cd tools\n"
            "# 2) make\n"
            "# 3) ./dsdgen -scale ${SCALE_FACTOR} -dir \"${OUT_DIR}\"\n\n"
            "echo \"Generate TPC-DS data using dsdgen into: ${OUT_DIR}\"\n"
        )


@dataclass
class TPCDSQueries(BenchmarkArtifact):
    """Generate TPC-DS query workload artifacts."""

    benchmark: str = "tpcds"
    artifact_type: str = "queries"

    def generate(self, output_dir: str | Path | None = None, force: bool = False) -> GenerationResult:
        root = self._require_output_dir(output_dir)
        out_dir = root / "tpcds" / "queries"
        out_dir.mkdir(parents=True, exist_ok=True)

        if not force:
            existing = self._load_existing(out_dir / "tpcds_queries_manifest.json", root)
            if existing is not None:
                print(f"[driftbench] TPC-DS queries already exist at {out_dir}. Reusing.")
                return existing
        print(f"[driftbench] Generating TPC-DS queries → {out_dir}")

        ids = list(range(1, 100))
        ids_file = self._write_text(
            out_dir / "query_ids.txt",
            "\n".join(f"query{idx:02d}" for idx in ids) + "\n",
        )
        benchbase_cfg = self._write_text(
            out_dir / "sample_tpcds_config.xml",
            self._benchbase_template(ids),
        )

        metadata = self._write_json(
            out_dir / "tpcds_queries_manifest.json",
            {
                "benchmark": self.benchmark,
                "artifact_type": self.artifact_type,
                "query_count": len(ids),
                "files": self._paths_relative_to(root, [ids_file, benchbase_cfg]),
                "note": "Use this as a starter workload profile; attach SQL text from your local TPC-DS kit query templates.",
            },
        )
        return self._result(root, [ids_file, benchbase_cfg], metadata)

    def _benchbase_template(self, ids: list[int]) -> str:
        weights = ",".join("1" for _ in ids)
        txns = "\n".join(
            (
                "        <transactiontype>\n"
                f"            <name>Q{idx}</name>\n"
                f"            <id>{idx}</id>\n"
                "        </transactiontype>"
            )
            for idx in ids
        )
        return (
            "<?xml version=\"1.0\"?>\n"
            "<parameters>\n"
            "    <type>POSTGRES</type>\n"
            "    <driver>org.postgresql.Driver</driver>\n"
            "    <url>jdbc:postgresql://localhost:5432/benchbase?sslmode=disable&amp;ApplicationName=tpcds</url>\n"
            "    <username>admin</username>\n"
            "    <password>password</password>\n"
            "    <terminals>1</terminals>\n"
            "    <works>\n"
            "        <work>\n"
            "            <serial>true</serial>\n"
            "            <rate>unlimited</rate>\n"
            f"            <weights>{weights}</weights>\n"
            "        </work>\n"
            "    </works>\n"
            "    <transactiontypes>\n"
            f"{txns}\n"
            "    </transactiontypes>\n"
            "</parameters>\n"
        )


def data(scale_factor: int | float = 10) -> TPCDSData:
    return TPCDSData(scale_factor=scale_factor)


def queries() -> TPCDSQueries:
    return TPCDSQueries()
